// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.
/** user-defined commands **/
export const commands = {
    /**
     * GET /api/v1/server_settings (unauthenticated)
     * Discovers server capabilities and authentication methods
     */
    async getServerSettings(url) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_server_settings", { url }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Authenticate with a Zulip server and start the event queue
     */
    async login(url, email, apiKey) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("login", { url, email, apiKey }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Disconnect from a Zulip server
     */
    async logout(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("logout", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch messages with narrow filters
     */
    async getMessages(orgId, narrow, anchor, numBefore, numAfter) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_messages", { orgId, narrow, anchor, numBefore, numAfter }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send a message
     */
    async sendMessage(orgId, msgType, to, content, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("send_message", { orgId, msgType, to, content, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Edit a message
     */
    async editMessage(orgId, messageId, content, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("edit_message", { orgId, messageId, content, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Delete a message
     */
    async deleteMessage(orgId, messageId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_message", { orgId, messageId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Add an emoji reaction
     */
    async addReaction(orgId, messageId, emojiName, emojiCode) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("add_reaction", { orgId, messageId, emojiName, emojiCode }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Remove an emoji reaction
     */
    async removeReaction(orgId, messageId, emojiName, emojiCode) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("remove_reaction", { orgId, messageId, emojiName, emojiCode }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update own presence status
     */
    async updatePresence(orgId, status) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_presence", { orgId, status }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send typing notification
     * `to` is a JSON string — either a JSON array of user IDs for DMs
     * or a single stream ID string for stream typing
     */
    async sendTyping(orgId, op, typingType, to, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("send_typing", { orgId, op, typingType, to, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Upload a file
     */
    async uploadFile(orgId, filePath) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("upload_file", { orgId, filePath }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update message flags (read, starred, etc.)
     */
    async updateMessageFlags(orgId, messages, op, flag) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_message_flags", { orgId, messages, op, flag }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Mark all messages in a stream as read
     */
    async markStreamAsRead(orgId, streamId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("mark_stream_as_read", { orgId, streamId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Mark all messages in a topic as read
     */
    async markTopicAsRead(orgId, streamId, topicName) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("mark_topic_as_read", { orgId, streamId, topicName }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get topics within a stream
     */
    async getStreamTopics(orgId, streamId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_stream_topics", { orgId, streamId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Subscribe to streams
     */
    async subscribeStream(orgId, streamNames) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("subscribe_stream", { orgId, streamNames }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Unsubscribe from streams
     */
    async unsubscribeStream(orgId, streamNames) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("unsubscribe_stream", { orgId, streamNames }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update Zulip user settings (syncs to server)
     * `settings_json` is a JSON string with Zulip API key names, e.g. `{"enter_sends": true}`
     */
    async updateZulipSettings(orgId, settingsJson) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_zulip_settings", { orgId, settingsJson }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch current Zulip user settings from server
     */
    async getZulipSettings(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_zulip_settings", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get all saved servers
     */
    async getServers() {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_servers") };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Add a server to the saved list
     */
    async addServer(server) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("add_server", { server }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Remove a server from the saved list
     */
    async removeServer(serverId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("remove_server", { serverId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get app config value as JSON string (caller parses)
     */
    async getConfig(key) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_config", { key }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Set app config value from JSON string (caller serializes)
     */
    async setConfig(key, value) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("set_config", { key, value }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Poll supervisor session state and events
     */
    async getSupervisorSession(orgId, topicScopeId, afterId, limit) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_supervisor_session", { orgId, topicScopeId, afterId, limit }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send a message to the supervisor
     */
    async postSupervisorMessage(orgId, topicScopeId, message, clientMsgId, streamId, streamName, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("post_supervisor_message", { orgId, topicScopeId, message, clientMsgId, streamId, streamName, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get task list for the supervisor dashboard
     */
    async getSupervisorSidebar(orgId, topicScopeId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_supervisor_sidebar", { orgId, topicScopeId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Control a task (pause/resume/cancel)
     */
    async controlSupervisorTask(orgId, topicScopeId, taskId, action) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("control_supervisor_task", { orgId, topicScopeId, taskId, action }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Reply to a task clarification question
     */
    async replyToTaskClarification(orgId, topicScopeId, taskId, message) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("reply_to_task_clarification", { orgId, topicScopeId, taskId, message }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get available AI providers and their auth status
     */
    async getFoundryProviders(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_foundry_providers", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get events for a specific task
     */
    async getTaskEvents(orgId, topicScopeId, taskId, afterId, limit) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_task_events", { orgId, topicScopeId, taskId, afterId, limit }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Start the supervisor SSE event stream for a topic.
     * This connects to the Zulip server's SSE proxy endpoint and emits
     * Tauri events as new supervisor events arrive in real time.
     */
    async startSupervisorStream(orgId, topicScopeId, afterId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("start_supervisor_stream", { orgId, topicScopeId, afterId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Stop the supervisor SSE event stream for an org.
     */
    async stopSupervisorStream(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("stop_supervisor_stream", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    }
};
/** tauri-specta globals **/
import { invoke as TAURI_INVOKE, } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
function __makeEvents__(mappings) {
    return new Proxy({}, {
        get: (_, event) => {
            const name = mappings[event];
            return new Proxy((() => { }), {
                apply: (_, __, [window]) => ({
                    listen: (arg) => window.listen(name, arg),
                    once: (arg) => window.once(name, arg),
                    emit: (arg) => window.emit(name, arg),
                }),
                get: (_, command) => {
                    switch (command) {
                        case "listen":
                            return (arg) => TAURI_API_EVENT.listen(name, arg);
                        case "once":
                            return (arg) => TAURI_API_EVENT.once(name, arg);
                        case "emit":
                            return (arg) => TAURI_API_EVENT.emit(name, arg);
                    }
                },
            });
        },
    });
}
