
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * GET /api/v1/server_settings (unauthenticated)
 * Discovers server capabilities and authentication methods
 */
async getServerSettings(url: string) : Promise<Result<ServerSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_settings", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Authenticate with a Zulip server and start the event queue
 */
async login(url: string, email: string, apiKey: string) : Promise<Result<LoginResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login", { url, email, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disconnect from a Zulip server
 */
async logout(orgId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout", { orgId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch messages with narrow filters
 */
async getMessages(orgId: string, narrow: NarrowFilter[], anchor: string, numBefore: number, numAfter: number) : Promise<Result<MessageResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_messages", { orgId, narrow, anchor, numBefore, numAfter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a message
 */
async sendMessage(orgId: string, msgType: string, to: string, content: string, topic: string | null) : Promise<Result<SendResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { orgId, msgType, to, content, topic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a message
 */
async editMessage(orgId: string, messageId: number, content: string | null, topic: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_message", { orgId, messageId, content, topic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a message
 */
async deleteMessage(orgId: string, messageId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_message", { orgId, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add an emoji reaction
 */
async addReaction(orgId: string, messageId: number, emojiName: string, emojiCode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_reaction", { orgId, messageId, emojiName, emojiCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove an emoji reaction
 */
async removeReaction(orgId: string, messageId: number, emojiName: string, emojiCode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_reaction", { orgId, messageId, emojiName, emojiCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update own presence status
 */
async updatePresence(orgId: string, status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_presence", { orgId, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send typing notification
 * `to` is a JSON string — either a JSON array of user IDs for DMs
 * or a single stream ID string for stream typing
 */
async sendTyping(orgId: string, op: string, typingType: string, to: string, topic: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_typing", { orgId, op, typingType, to, topic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upload a file
 */
async uploadFile(orgId: string, filePath: string) : Promise<Result<UploadResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_file", { orgId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update message flags (read, starred, etc.)
 */
async updateMessageFlags(orgId: string, messages: number[], op: string, flag: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_message_flags", { orgId, messages, op, flag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark all messages in a stream as read
 */
async markStreamAsRead(orgId: string, streamId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_stream_as_read", { orgId, streamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark all messages in a topic as read
 */
async markTopicAsRead(orgId: string, streamId: number, topicName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_topic_as_read", { orgId, streamId, topicName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get topics within a stream
 */
async getStreamTopics(orgId: string, streamId: number) : Promise<Result<Topic[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stream_topics", { orgId, streamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Subscribe to streams
 */
async subscribeStream(orgId: string, streamNames: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_stream", { orgId, streamNames }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unsubscribe from streams
 */
async unsubscribeStream(orgId: string, streamNames: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unsubscribe_stream", { orgId, streamNames }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update Zulip user settings (syncs to server)
 * `settings_json` is a JSON string with Zulip API key names, e.g. `{"enter_sends": true}`
 */
async updateZulipSettings(orgId: string, settingsJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_zulip_settings", { orgId, settingsJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch current Zulip user settings from server
 */
async getZulipSettings(orgId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_zulip_settings", { orgId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all saved servers
 */
async getServers() : Promise<Result<SavedServer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a server to the saved list
 */
async addServer(server: SavedServer) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_server", { server }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a server from the saved list
 */
async removeServer(serverId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_server", { serverId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get app config value as JSON string (caller parses)
 */
async getConfig(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set app config value from JSON string (caller serializes)
 */
async setConfig(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Poll supervisor session state and events
 */
async getSupervisorSession(orgId: string, topicScopeId: string, afterId: number, limit: number) : Promise<Result<SupervisorSessionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_supervisor_session", { orgId, topicScopeId, afterId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a message to the supervisor
 */
async postSupervisorMessage(orgId: string, topicScopeId: string, message: string, clientMsgId: string, streamId: number | null, streamName: string | null, topic: string | null) : Promise<Result<SupervisorMessageResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("post_supervisor_message", { orgId, topicScopeId, message, clientMsgId, streamId, streamName, topic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get task list for the supervisor dashboard
 */
async getSupervisorSidebar(orgId: string, topicScopeId: string) : Promise<Result<SupervisorSidebarResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_supervisor_sidebar", { orgId, topicScopeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Control a task (pause/resume/cancel)
 */
async controlSupervisorTask(orgId: string, topicScopeId: string, taskId: string, action: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("control_supervisor_task", { orgId, topicScopeId, taskId, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reply to a task clarification question
 */
async replyToTaskClarification(orgId: string, topicScopeId: string, taskId: string, message: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reply_to_task_clarification", { orgId, topicScopeId, taskId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get available AI providers and their auth status
 */
async getFoundryProviders(orgId: string) : Promise<Result<FoundryProvidersResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_foundry_providers", { orgId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get events for a specific task
 */
async getTaskEvents(orgId: string, topicScopeId: string, taskId: string, afterId: number, limit: number) : Promise<Result<TaskEventsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_events", { orgId, topicScopeId, taskId, afterId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the supervisor SSE event stream for a topic.
 * This connects to the Zulip server's SSE proxy endpoint and emits
 * Tauri events as new supervisor events arrive in real time.
 */
async startSupervisorStream(orgId: string, topicScopeId: string, afterId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_supervisor_stream", { orgId, topicScopeId, afterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the supervisor SSE event stream for an org.
 */
async stopSupervisorStream(orgId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_supervisor_stream", { orgId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthMethods = { password?: boolean; google?: boolean; github?: boolean; ldap?: boolean; dev?: boolean }
/**
 * Display recipient — either a stream name (string) or list of users (DMs)
 */
export type DisplayRecipient = string | DisplayRecipientUser[]
/**
 * User in a DM display_recipient
 */
export type DisplayRecipientUser = { id: number; email: string; full_name: string }
/**
 * Provider authentication entry
 */
export type FoundryProviderAuth = { provider: string; display_name?: string; auth_modes?: string[]; oauth_configured?: boolean; credential_status?: string | null }
/**
 * Response from GET /json/foundry/providers/auth
 */
export type FoundryProvidersResponse = { providers?: FoundryProviderAuth[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Result of login flow
 */
export type LoginResult = { org_id: string; realm_name: string; realm_icon: string; queue_id: string; 
/**
 * The logged-in user's ID (from Zulip register response)
 */
user_id: number | null; subscriptions: Subscription[]; users: User[] }
/**
 * A Zulip message
 */
export type Message = { id: number; sender_id: number; sender_full_name: string; sender_email: string; type: string; content: string; subject: string; timestamp: number; stream_id: number | null; flags?: string[]; reactions?: Reaction[]; avatar_url: string | null; display_recipient: DisplayRecipient }
/**
 * GET /api/v1/messages response
 */
export type MessageResponse = { messages: Message[]; found_newest: boolean; found_oldest: boolean; found_anchor: boolean }
/**
 * Narrow filter for message queries
 */
export type NarrowFilter = { operator: string; operand: NarrowOperand }
/**
 * Narrow operand — either a text string or a list of user IDs
 */
export type NarrowOperand = string | number[]
/**
 * Emoji reaction
 */
export type Reaction = { emoji_name: string; emoji_code: string; reaction_type: string; user_id: number }
/**
 * Saved server configuration
 */
export type SavedServer = { id: string; url: string; email: string; api_key: string; realm_name: string; realm_icon: string }
/**
 * Send message result
 */
export type SendResult = { id: number }
/**
 * Server settings returned by GET /api/v1/server_settings (unauthenticated)
 */
export type ServerSettings = { zulip_version: string; zulip_feature_level: number; push_notifications_enabled: boolean; realm_name: string; realm_icon: string; realm_description: string; authentication_methods?: AuthMethods }
/**
 * Stream/channel subscription
 */
export type Subscription = { stream_id: number; name: string; description?: string; color?: string; invite_only?: boolean; is_muted?: boolean; pin_to_top?: boolean }
/**
 * A single event in the supervisor timeline
 */
export type SupervisorEvent = { id: number; topic_scope_id: string; session_id: string; ts: string; 
/**
 * Event kind: "message", "thinking", "tool_call", "tool_result",
 * "dispatch_result", "plan_draft", "assistant"
 */
kind: string; 
/**
 * Role: "user", "assistant", "system"
 */
role: string; author_id?: string | null; author_name?: string | null; content_md?: string; 
/**
 * Polymorphic payload - structure varies by event kind
 */
payload?: JsonValue; client_msg_id?: string | null }
/**
 * Response from POST /json/foundry/topics/{scope}/supervisor/message
 */
export type SupervisorMessageResponse = { session?: SupervisorSession | null; events?: SupervisorEvent[] }
/**
 * A supervisor session tied to a topic scope
 */
export type SupervisorSession = { session_id: string; topic_scope_id: string; status: string; updated_at?: string | null; metadata?: SupervisorSessionMetadata }
/**
 * Metadata about the supervisor session engine
 */
export type SupervisorSessionMetadata = { engine?: string | null; moltis_model?: string | null }
/**
 * Response from GET /json/foundry/topics/{scope}/supervisor/session
 */
export type SupervisorSessionResponse = { session?: SupervisorSession | null; events?: SupervisorEvent[] }
/**
 * Response from GET /json/foundry/topics/{scope}/sidebar
 */
export type SupervisorSidebarResponse = { tasks?: SupervisorTask[] }
/**
 * A task entry from the supervisor sidebar/dashboard
 */
export type SupervisorTask = { task_id: string; title?: string; assigned_role?: string; status?: string; activity?: string | null; last_updated?: string | null; preview_url?: string | null; branch_name?: string | null; turns_used?: number | null; tokens_used?: number | null; usd_estimate?: number | null; result_text?: string | null; error_text?: string | null; clarification_requested?: boolean; approved?: boolean; artifacts?: JsonValue[]; blockers?: string[] }
/**
 * Task event from the task event stream
 */
export type TaskEvent = { id: number; task_id: string; ts: string; level?: string; event_type?: string; message?: string; data?: JsonValue }
/**
 * Response from GET /json/foundry/topics/{scope}/tasks/{task_id}/events
 */
export type TaskEventsResponse = { task_id: string; events?: TaskEvent[] }
/**
 * Topic within a stream
 */
export type Topic = { name: string; max_id: number }
/**
 * Upload file result
 */
export type UploadResult = { url: string; uri?: string | null }
/**
 * User profile
 */
export type User = { user_id: number; email: string; full_name: string; is_active?: boolean; is_bot?: boolean; is_admin?: boolean; avatar_url?: string | null; timezone?: string; role: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
