// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.
/** user-defined commands **/
export const commands = {
    /**
     * GET /api/v1/server_settings (unauthenticated)
     * Discovers server capabilities and authentication methods
     */
    async getServerSettings(url) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_server_settings", { url }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Authenticate with a Zulip server and start the event queue
     */
    async login(url, email, apiKey) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("login", { url, email, apiKey }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Exchange a password for an API key using Zulip's fetch_api_key endpoint
     */
    async fetchApiKey(url, username, password) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("fetch_api_key", { url, username, password }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Open an app-owned sign-in window for Zulip external authentication flows.
     */
    async openExternalAuthWindow(url) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("open_external_auth_window", { url }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Disconnect from a Zulip server
     */
    async logout(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("logout", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch messages with narrow filters
     */
    async getMessages(orgId, narrow, anchor, numBefore, numAfter) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_messages", { orgId, narrow, anchor, numBefore, numAfter }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send a message
     */
    async sendMessage(orgId, msgType, to, content, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("send_message", { orgId, msgType, to, content, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Edit a message
     */
    async editMessage(orgId, messageId, content, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("edit_message", { orgId, messageId, content, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Delete a message
     */
    async deleteMessage(orgId, messageId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_message", { orgId, messageId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Add an emoji reaction
     */
    async addReaction(orgId, messageId, emojiName, emojiCode) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("add_reaction", { orgId, messageId, emojiName, emojiCode }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Remove an emoji reaction
     */
    async removeReaction(orgId, messageId, emojiName, emojiCode) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("remove_reaction", { orgId, messageId, emojiName, emojiCode }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update own presence status
     */
    async updatePresence(orgId, status) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_presence", { orgId, status }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send typing notification
     * `to` is a JSON string — either a JSON array of user IDs for DMs
     * or a single stream ID string for stream typing
     */
    async sendTyping(orgId, op, typingType, to, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("send_typing", { orgId, op, typingType, to, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Save bytes to a temporary file and return its path (for paste/drag-drop uploads)
     */
    async saveTempFile(fileName, data) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("save_temp_file", { fileName, data }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Upload a file
     */
    async uploadFile(orgId, filePath) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("upload_file", { orgId, filePath }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch an authenticated media URL and convert it to a data URL for the webview.
     */
    async fetchAuthenticatedMediaDataUrl(orgId, mediaUrl) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("fetch_authenticated_media_data_url", { orgId, mediaUrl }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update message flags (read, starred, etc.)
     */
    async updateMessageFlags(orgId, messages, op, flag) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_message_flags", { orgId, messages, op, flag }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Mark all messages in a stream as read
     */
    async markStreamAsRead(orgId, streamId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("mark_stream_as_read", { orgId, streamId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Mark all messages in a topic as read
     */
    async markTopicAsRead(orgId, streamId, topicName) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("mark_topic_as_read", { orgId, streamId, topicName }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get topics within a stream
     */
    async getStreamTopics(orgId, streamId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_stream_topics", { orgId, streamId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Subscribe to streams
     */
    async subscribeStream(orgId, streamNames) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("subscribe_stream", { orgId, streamNames }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Unsubscribe from streams
     */
    async unsubscribeStream(orgId, streamNames) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("unsubscribe_stream", { orgId, streamNames }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update one or more subscription properties for channels the user is subscribed to.
     */
    async updateSubscriptionProperties(orgId, subscriptionData) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_subscription_properties", { orgId, subscriptionData }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update the current user's topic visibility policy within a channel.
     */
    async updateTopicVisibilityPolicy(orgId, streamId, topic, visibilityPolicy) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_topic_visibility_policy", { orgId, streamId, topic, visibilityPolicy }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Move or rename all messages in a topic.
     */
    async moveTopic(orgId, request) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("move_topic", { orgId, request }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Resolve or unresolve all messages in a topic.
     */
    async setTopicResolved(orgId, request) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("set_topic_resolved", { orgId, request }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update Zulip user settings (syncs to server)
     * `settings_json` is a JSON string with Zulip API key names, e.g. `{"enter_sends": true}`
     */
    async updateZulipSettings(orgId, settingsJson) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_zulip_settings", { orgId, settingsJson }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch current Zulip user settings from server
     */
    async getZulipSettings(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_zulip_settings", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch the current set of users from the Zulip server.
     */
    async getUsers(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_users", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Reactivate a deactivated user.
     */
    async reactivateUser(orgId, userId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("reactivate_user", { orgId, userId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch presence data for the current organization.
     */
    async getRealmPresence(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_realm_presence", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch a typed snapshot of organization settings and configured email domains.
     */
    async getRealmSettings(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_realm_settings", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update organization-level settings using Zulip API key names.
     * `settings_json` is a JSON string such as `{"name":"Acme","invite_required":true}`.
     */
    async updateRealmSettings(orgId, settingsJson) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_realm_settings", { orgId, settingsJson }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Add a new organization email domain restriction.
     */
    async createRealmDomain(orgId, domain, allowSubdomains) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("create_realm_domain", { orgId, domain, allowSubdomains }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update the subdomain policy for an organization email domain.
     */
    async updateRealmDomain(orgId, domain, allowSubdomains) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_realm_domain", { orgId, domain, allowSubdomains }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Remove an organization email domain restriction.
     */
    async deleteRealmDomain(orgId, domain) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_realm_domain", { orgId, domain }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch all manageable invitations.
     */
    async getInvites(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_invites", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send email invitations.
     */
    async sendInvites(orgId, inviteeEmails, inviteExpiresInMinutes, inviteAs, streamIds) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("send_invites", { orgId, inviteeEmails, inviteExpiresInMinutes, inviteAs, streamIds }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Revoke an email invitation.
     */
    async revokeInvite(orgId, inviteId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("revoke_invite", { orgId, inviteId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Resend an email invitation.
     */
    async resendInvite(orgId, inviteId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("resend_invite", { orgId, inviteId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch user groups for the current organization.
     */
    async getUserGroups(orgId, includeDeactivatedGroups) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_user_groups", { orgId, includeDeactivatedGroups }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Create a user group.
     */
    async createUserGroup(orgId, name, description, members) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("create_user_group", { orgId, name, description, members }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update the metadata for a user group.
     */
    async updateUserGroup(orgId, userGroupId, name, description) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_user_group", { orgId, userGroupId, name, description }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Deactivate a user group.
     */
    async deactivateUserGroup(orgId, userGroupId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("deactivate_user_group", { orgId, userGroupId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch all realm linkifiers.
     */
    async getLinkifiers(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_linkifiers", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Change linkifier evaluation order.
     */
    async reorderLinkifiers(orgId, orderedLinkifierIds) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("reorder_linkifiers", { orgId, orderedLinkifierIds }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Create a linkifier.
     */
    async createLinkifier(orgId, pattern, urlTemplate) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("create_linkifier", { orgId, pattern, urlTemplate }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Update a linkifier.
     */
    async updateLinkifier(orgId, filterId, pattern, urlTemplate) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("update_linkifier", { orgId, filterId, pattern, urlTemplate }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Delete a linkifier.
     */
    async deleteLinkifier(orgId, filterId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_linkifier", { orgId, filterId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch custom emoji for the organization.
     */
    async getRealmEmoji(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_realm_emoji", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Upload a custom emoji asset.
     */
    async uploadCustomEmoji(orgId, emojiName, filePath) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("upload_custom_emoji", { orgId, emojiName, filePath }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Deactivate a custom emoji.
     */
    async deleteCustomEmoji(orgId, emojiName) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_custom_emoji", { orgId, emojiName }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Upload an organization icon asset.
     */
    async uploadRealmIcon(orgId, filePath) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("upload_realm_icon", { orgId, filePath }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Reset the organization icon to the default source.
     */
    async deleteRealmIcon(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_realm_icon", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Upload a light or dark organization logo asset.
     */
    async uploadRealmLogo(orgId, filePath, night) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("upload_realm_logo", { orgId, filePath, night }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Reset the light or dark organization logo to the default source.
     */
    async deleteRealmLogo(orgId, night) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("delete_realm_logo", { orgId, night }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch bots the current user can administer.
     */
    async getBots(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_bots", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Create a bot or integration user.
     */
    async createBot(orgId, fullName, shortName, botType, serviceName, payloadUrl) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("create_bot", { orgId, fullName, shortName, botType, serviceName, payloadUrl }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Fetch the API key for a bot.
     */
    async getBotApiKey(orgId, botId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_bot_api_key", { orgId, botId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get all saved servers
     */
    async getServers() {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_servers") };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get saved servers along with whether they are currently connected in this app session.
     */
    async getSavedServerStatuses() {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_saved_server_statuses") };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Add a server to the saved list
     */
    async addServer(server) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("add_server", { server }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Remove a server from the saved list
     */
    async removeServer(serverId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("remove_server", { serverId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Return the native desktop settings contract as a typed object.
     */
    async getDesktopSettings() {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_desktop_settings") };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Persist the native desktop settings contract.
     */
    async setDesktopSettings(settings) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("set_desktop_settings", { settings }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Report native/backend feature support for frontend planning and gating.
     */
    async getDesktopCapabilities() {
        return await TAURI_INVOKE("get_desktop_capabilities");
    },
    /**
     * Update the platform unread badge count on the main window.
     */
    async setUnreadBadgeCount(count) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("set_unread_badge_count", { count }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get app config value as JSON string (caller parses)
     */
    async getConfig(key) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_config", { key }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Set app config value from JSON string (caller serializes)
     */
    async setConfig(key, value) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("set_config", { key, value }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Poll supervisor session state and events
     */
    async getSupervisorSession(orgId, topicScopeId, afterId, limit) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_supervisor_session", { orgId, topicScopeId, afterId, limit }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Send a message to the supervisor
     */
    async postSupervisorMessage(orgId, topicScopeId, message, clientMsgId, streamId, streamName, topic) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("post_supervisor_message", { orgId, topicScopeId, message, clientMsgId, streamId, streamName, topic }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get task list for the supervisor dashboard
     */
    async getSupervisorSidebar(orgId, topicScopeId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_supervisor_sidebar", { orgId, topicScopeId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Control a task (pause/resume/cancel)
     */
    async controlSupervisorTask(orgId, topicScopeId, taskId, action) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("control_supervisor_task", { orgId, topicScopeId, taskId, action }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Reply to a task clarification question
     */
    async replyToTaskClarification(orgId, topicScopeId, taskId, message) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("reply_to_task_clarification", { orgId, topicScopeId, taskId, message }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get available AI providers and their auth status
     */
    async getFoundryProviders(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_foundry_providers", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Connect a Foundry provider using an API key credential
     */
    async connectFoundryProvider(orgId, provider, apiKey, label) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("connect_foundry_provider", { orgId, provider, apiKey, label }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Disconnect a Foundry provider credential
     */
    async disconnectFoundryProvider(orgId, provider) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("disconnect_foundry_provider", { orgId, provider }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Start a Foundry provider OAuth flow
     */
    async startFoundryProviderOauth(orgId, provider, redirectUri) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("start_foundry_provider_oauth", { orgId, provider, redirectUri }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Get events for a specific task
     */
    async getTaskEvents(orgId, topicScopeId, taskId, afterId, limit) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("get_task_events", { orgId, topicScopeId, taskId, afterId, limit }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Start the supervisor SSE event stream for a topic.
     * This connects to the Zulip server's SSE proxy endpoint and emits
     * Tauri events as new supervisor events arrive in real time.
     */
    async startSupervisorStream(orgId, topicScopeId, afterId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("start_supervisor_stream", { orgId, topicScopeId, afterId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    },
    /**
     * Stop the supervisor SSE event stream for an org.
     */
    async stopSupervisorStream(orgId) {
        try {
            return { status: "ok", data: await TAURI_INVOKE("stop_supervisor_stream", { orgId }) };
        }
        catch (e) {
            if (e instanceof Error)
                throw e;
            else
                return { status: "error", error: e };
        }
    }
};
/** tauri-specta globals **/
import { invoke as TAURI_INVOKE, } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
function __makeEvents__(mappings) {
    return new Proxy({}, {
        get: (_, event) => {
            const name = mappings[event];
            return new Proxy((() => { }), {
                apply: (_, __, [window]) => ({
                    listen: (arg) => window.listen(name, arg),
                    once: (arg) => window.once(name, arg),
                    emit: (arg) => window.emit(name, arg),
                }),
                get: (_, command) => {
                    switch (command) {
                        case "listen":
                            return (arg) => TAURI_API_EVENT.listen(name, arg);
                        case "once":
                            return (arg) => TAURI_API_EVENT.once(name, arg);
                        case "emit":
                            return (arg) => TAURI_API_EVENT.emit(name, arg);
                    }
                },
            });
        },
    });
}
